sudo: required
language: node_js
node_js:
  - "8.12.0"
cache:
  directories:
    - "node_modules"
services:
  - docker
before_install:
  - docker build -t rajatreactapp .
  - docker run -p 127.0.0.1:4000:80 rajatreactapp
  - docker ps -a
script:
  - npm test
